### ISSUE TITLE
Theme Blog with TailwindCSS

### ISSUE THREAD

**Issue by XIPEGM** [lumeland/themes#1]
Base the **lume-simple-theme-blog**, but With **TailwindCSS**, clean and beautyful.  

[lume_theme_blog](https://deno.land/x/lume_theme_blog@v0.2) 

Demo:

[My Blog](https://istudymen.github.io/)

**Comment by oscarotero** [comment]
That's great! Thanks so much!

As a suggestion, I think it would be nice if the footer was always at the bottom of the windows. If the page has not many content, it's in the middle:

<img width="1470" alt="imaxe" src="https://github.com/lumeland/themes/assets/377873/385b4934-ef93-4994-b5e4-48ec77b80023">

A solution is to convert the body to a `grid`:

```css
body {
  display: grid;
  min-height: 100vh;
  grid-template-rows: auto 1fr auto;
}
```

With these changes it looks like this:

<img width="1349" alt="imaxe" src="https://github.com/lumeland/themes/assets/377873/d3e801fd-ae65-444e-aba1-5673fd945a99">
